#ifndef __COLUMBUS_H__
#define __COLUMBUS_H__

#include <linux/sizes.h>

#define CONFIG_SYS_CACHELINE_SIZE	32

/* uboot size limit:1M */
#define CONFIG_BOARD_SIZE_LIMIT		1048576

#define CONFIG_NR_DRAM_BANKS		1
#define CONFIG_SYS_SDRAM_BASE		0x08000000
#define CONFIG_SYS_TEXT_BASE		0x0bf80000
#define CONFIG_SYS_LOAD_ADDR		CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_INIT_SP_ADDR 	(CONFIG_SYS_TEXT_BASE + SZ_4M - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_MALLOC_LEN		(32 << 20)

#define CONFIG_ENV_IS_NOWHERE
#define CONFIG_ENV_SIZE			SZ_128K

#define CONFIG_DT_LOAD_ADDR		0x0c080000
#define CONFIG_EXTRA_ENV_SETTINGS \
	CONFIG_EXTRA_ENV_SETTINGS_BOARD \
	"fdtcontroladdr=" __stringify(CONFIG_DT_LOAD_ADDR) "\0" \
	"bootfile=kernel.itb\0"

#define CONFIG_SYS_CBSIZE		1024
#define CONFIG_SYS_MAXARGS		16

#define CONFIG_BAUDRATE			115200
#define CONFIG_SYS_NS16550_MEM32

/* No NOR flash */
#define CONFIG_SYS_NO_FLASH

#define CONFIG_BOARD_EARLY_INIT_F

#define CONFIG_OF_LIBFDT

#endif
